# Generated by Django 3.1.1 on 2020-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanagement', '0003_auto_20200429_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
