# Generated by Django 2.2.5 on 2020-11-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenancemanagement', '0016_auto_20201014_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('recurrence', models.CharField(max_length=100)),
                ('is_activated', models.BooleanField(default=True)),
                ('job_id', models.CharField(default='', max_length=100)),
                ('equipment', models.ForeignKey(help_text='The equipment for which you wish to get value', on_delete=django.db.models.deletion.CASCADE, related_name='dataprovider_set', related_query_name='dataprovider', to='maintenancemanagement.Equipment', verbose_name='Linked equipment')),
                ('field_object', models.ForeignKey(help_text='The field for which you wish to update value', on_delete=django.db.models.deletion.CASCADE, related_name='field_set', related_query_name='field_object', to='maintenancemanagement.FieldObject', verbose_name='Linked field')),
            ],
        ),
    ]
