# Generated by Django 3.1.1 on 2020-11-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenancemanagement', '0016_auto_20201014_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('recurrence', models.CharField(max_length=100)),
                ('activated', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(help_text='The equipment for which you wish to get value', on_delete=django.db.models.deletion.CASCADE, related_name='plugin_set', related_query_name='plugin', to='maintenancemanagement.equipment', verbose_name='Linked equipment')),
                ('field', models.ForeignKey(help_text='The field for which you wish to update value', on_delete=django.db.models.deletion.CASCADE, related_name='field_set', related_query_name='field_object', to='maintenancemanagement.fieldobject', verbose_name='Linked field')),
            ],
        ),
    ]
