# Generated by Django 3.1.1 on 2020-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='is_activated',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
