# Generated by Django 3.1.1 on 2020-11-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20201103_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='activated',
            new_name='is_activated',
        ),
    ]
