# Generated by Django 2.2.5 on 2020-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_dataprovider_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=502, null=True),
        ),
    ]
