# Generated by Django 3.1.1 on 2020-11-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0016_auto_20201014_0737'),
        ('utils', '0004_plugin_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plugin',
            new_name='DataProvider',
        ),
    ]
