# Generated by Django 3.1.1 on 2020-11-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0016_auto_20201014_0737'),
        ('utils', '0005_auto_20201104_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='equipment',
            field=models.ForeignKey(help_text='The equipment for which you wish to get value', on_delete=django.db.models.deletion.CASCADE, related_name='dataprovider_set', related_query_name='dataprovider', to='maintenancemanagement.equipment', verbose_name='Linked equipment'),
        ),
    ]
