# Generated by Django 3.1.1 on 2020-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20201104_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovider',
            name='job',
            field=models.CharField(default='', max_length=100),
        ),
    ]
