# Generated by Django 3.1.1 on 2020-11-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_dataprovider_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprovider',
            old_name='job',
            new_name='job_id',
        ),
    ]
