# Generated by Django 3.0.4 on 2020-04-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_equipment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_set', related_query_name='field', to='maintenancemanagement.FieldGroup')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(blank=True, help_text='Specific fields for this equipment type', related_name='equipmentType_set', related_query_name='equipmentType', to='maintenancemanagement.Field', verbose_name='Equipment Type Field')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_set', related_query_name='equipment', to='maintenancemanagement.EquipmentType', verbose_name='Equipment Type')),
            ],
        ),
    ]
