# Generated by Django 3.0.4 on 2020-04-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('usersmanagement', '0003_auto_20200429_0911'),
        ('maintenancemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields_groups', models.ManyToManyField(help_text='Fields Groups of the Task Type', related_name='task_type_set', related_query_name='tasktype', to='maintenancemanagement.FieldGroup', verbose_name='Fields Group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('end_date', models.DateField()),
                ('time', models.DurationField()),
                ('is_template', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(blank=True, help_text='The equipment assigned to the task', on_delete=django.db.models.deletion.CASCADE, related_name='task_set', related_query_name='task', to='maintenancemanagement.Equipment', verbose_name='Assigned equipment')),
                ('task_type', models.ForeignKey(blank=True, help_text='The type of this task', on_delete=django.db.models.deletion.CASCADE, related_name='task_set', related_query_name='task', to='maintenancemanagement.TaskType', verbose_name='Task Type')),
                ('teams', models.ManyToManyField(blank=True, help_text='The team(s) assigned to this task', related_name='task_set', related_query_name='task', to='usersmanagement.Team', verbose_name='Assigned team(s)')),
            ],
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_set', related_query_name='value', to='maintenancemanagement.Field')),
            ],
        ),
        migrations.CreateModel(
            name='FieldObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.CharField(default='', max_length=100)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_set', related_query_name='object', to='maintenancemanagement.Field')),
                ('field_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_set', related_query_name='object', to='maintenancemanagement.FieldValue')),
            ],
        ),
    ]
