# Generated by Django 3.0.4 on 2020-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0002_fieldobject_fieldvalue_task_tasktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('is_notice', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='equipment_set', related_query_name='equipment', to='maintenancemanagement.Files', verbose_name='Equipment File'),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='task_set', related_query_name='task', to='maintenancemanagement.Files', verbose_name='Task File'),
        ),
    ]
