# Generated by Django 3.0.4 on 2020-04-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanagement', '0003_auto_20200429_0911'),
        ('maintenancemanagement', '0003_auto_20200429_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='The equipment assigned to the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_set', related_query_name='task', to='maintenancemanagement.Equipment', verbose_name='Assigned equipment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_set', related_query_name='task', to='maintenancemanagement.Files', verbose_name='Task File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, help_text='The type of this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_set', related_query_name='task', to='maintenancemanagement.TaskType', verbose_name='Task Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='The team(s) assigned to this task', null=True, related_name='task_set', related_query_name='task', to='usersmanagement.Team', verbose_name='Assigned team(s)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
