# Generated by Django 3.0.4 on 2020-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("maintenancemanagement", "0006_auto_20200504_1221")]

    operations = [
        migrations.AddField(
            model_name="fieldobject",
            name="description",
            field=models.CharField(default="", max_length=100),
        )
    ]
