# Generated by Django 3.0.4 on 2020-05-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("maintenancemanagement", "0007_fieldobject_description")]

    operations = [migrations.RenameModel(old_name="Files", new_name="File")]
