# Generated by Django 3.0.4 on 2020-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0008_auto_20200504_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='fields',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='fields_groups',
            field=models.ManyToManyField(blank=True, help_text='Specific fields for this equipment type', related_name='equipmentType_set', related_query_name='equipmentType', to='maintenancemanagement.FieldGroup', verbose_name='Equipment Type Field'),
        ),
        migrations.AddField(
            model_name='task',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
