# Generated by Django 3.0.4 on 2020-05-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0009_auto_20200505_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fields_groups',
        ),
    ]
