# Generated by Django 3.1.1 on 2020-09-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0010_remove_task_fields_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='The type of equipment assigned to the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_set', related_query_name='task', to='maintenancemanagement.equipmenttype', verbose_name='Assigned equipment type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
