# Generated by Django 3.1.1 on 2020-10-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0011_auto_20200928_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldobject',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldobject',
            name='value',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
