# Generated by Django 3.1.1 on 2020-10-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0012_auto_20201006_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldobject',
            name='field_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_set', related_query_name='object', to='maintenancemanagement.fieldvalue'),
        ),
    ]
