# Generated by Django 3.1.1 on 2020-10-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0013_auto_20201008_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_set', related_query_name='field', to='maintenancemanagement.fieldgroup'),
        ),
    ]
