# Generated by Django 3.1.1 on 2020-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0015_auto_20201013_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='over',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
