# Generated by Django 3.1.1 on 2020-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0017_auto_20201130_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_triggered',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
