# Generated by Django 3.1.1 on 2020-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanagement', '0018_auto_20201207_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_triggered',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
